INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Yago Novaes', 'breno77@gmail.com', '(051) 7448-7987', 'Barros', 'AP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Isadora Castro', 'matheus03@rezende.br', '+55 61 1452-9335', 'Freitas de Minas', 'BA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Laís Rodrigues', 'catarina74@cavalcanti.br', '(051) 5999 5005', 'Rodrigues', 'CE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Davi Luiz Pereira', 'mmoraes@ig.com.br', '+55 31 1904-6184', 'Porto dos Dourados', 'ES');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Leandro Gomes', 'ana-vitoria67@gomes.com', '0800-073-3103', 'Santos', 'BA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Raul da Luz', 'nathan40@da.com', '+55 21 5218-7754', 'Lima de Minas', 'PI');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Clara Araújo', 'leonardoalves@gmail.com', '(081) 4244-7059', 'Teixeira de Costa', 'MA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Yuri Teixeira', 'uduarte@ig.com.br', '(071) 0887 8440', 'Nunes', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Manuela Caldeira', 'flopes@da.com', '51 5040 7054', 'Jesus', 'BA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Vitor Hugo Peixoto', 'qda-luz@uol.com.br', '31 1353-2450', 'Nunes', 'SP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Levi Correia', 'fernandescatarina@cunha.br', '0900-539-4060', 'da Rosa do Sul', 'SC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Juliana Costa', 'lnunes@uol.com.br', '+55 (071) 5079-9475', 'Silva da Prata', 'AC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Luiz Henrique Costa', 'vitor-hugobarbosa@campos.com', '+55 (084) 8641-0280', 'Ribeiro', 'ES');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Juliana Sales', 'vitor-gabrieldias@azevedo.com', '(084) 7929-2023', 'Nunes', 'SP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Alícia Silva', 'rochaluiz-fernando@uol.com.br', '61 2391 8918', 'da Mata', 'MT');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Evelyn Barbosa', 'mendesheitor@da.br', '(081) 5146-0870', 'Araújo', 'AP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Davi Lucca Oliveira', 'rodriguesdaniela@hotmail.com', '84 8562 9733', 'Fogaça do Norte', 'PE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Henrique Campos', 'joaquim61@monteiro.br', '+55 31 1265 3335', 'Moreira', 'MA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Beatriz Nogueira', 'cardosomaria-alice@gmail.com', '+55 81 1396 6006', 'das Neves da Serra', 'SC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Maria Luiza Aragão', 'ana-carolina76@melo.com', '0300 915 8894', 'Moura Alegre', 'RJ');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Letícia Pinto', 'fernandesheloisa@caldeira.net', '0800-634-6052', 'Ferreira Grande', 'PE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Marcela Ferreira', 'carolina22@farias.com', '+55 (061) 1887-7515', 'Monteiro da Praia', 'RO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Isis Costa', 'mendesmaria-fernanda@pires.net', '(071) 1125 2871', 'Carvalho da Serra', 'SP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Gustavo Henrique Barros', 'kvieira@uol.com.br', '+55 (081) 4169 6408', 'Barros Grande', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Heloísa Monteiro', 'portorafaela@bol.com.br', '+55 51 6046 5000', 'Rezende', 'MT');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Stella Silva', 'laisrodrigues@silveira.com', '+55 61 6876 8986', 'Cardoso do Galho', 'MA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Gabriela da Rocha', 'jcorreia@ig.com.br', '(084) 1020 8390', 'Cunha das Pedras', 'PA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Srta. Cecília Porto', 'sophia93@carvalho.com', '+55 21 9697-7733', 'Oliveira', 'RR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Stella Campos', 'ceciliacampos@hotmail.com', '51 7513 6895', 'Cavalcanti da Praia', 'AP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Miguel Barbosa', 'ana-liviamendes@alves.com', '(021) 6899-6140', 'Oliveira Alegre', 'RR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('André Ferreira', 'leandrosales@ig.com.br', '(021) 4228-1909', 'Barbosa', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Henrique Castro', 'nrezende@moreira.br', '(011) 4152-1587', 'da Paz', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Vitor Hugo Nunes', 'maria-julia89@uol.com.br', '84 5013-8568', 'Nunes do Galho', 'RO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Paulo da Cunha', 'caio59@ig.com.br', '+55 51 4745 0518', 'da Cruz do Galho', 'SC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Luiz Miguel das Neves', 'bernardocorreia@ig.com.br', '(084) 0307 4479', 'Araújo da Praia', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Arthur Cunha', 'imoraes@gomes.br', '+55 (084) 0050-7806', 'da Cunha', 'PI');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Antônio da Mata', 'upires@uol.com.br', '71 8948 4513', 'Pereira de Martins', 'RS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Sr. Luiz Miguel Peixoto', 'henrique42@uol.com.br', '(084) 2867-5500', 'da Rocha', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Thiago Castro', 'monteiromariane@nogueira.com', '84 3055-8311', 'Moreira', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Augusto da Rosa', 'nina88@rezende.org', '+55 61 3076-8529', 'Cardoso', 'MA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Brenda Fogaça', 'qrezende@gmail.com', '+55 (021) 6031-2949', 'Farias de Costa', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Ana Carolina Mendes', 'agathasales@da.com', '+55 41 4067 1030', 'Gonçalves de Lopes', 'AC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Lara Cavalcanti', 'marcos-vinicius36@vieira.br', '71 9737 6160', 'Gomes', 'SE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Marcelo Barros', 'aragaoalice@da.com', '0900 340 0065', 'Ribeiro', 'TO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Milena Pires', 'sda-mata@caldeira.com', '(061) 7236-2705', 'Moraes', 'MT');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Lorena Moraes', 'piresjoaquim@uol.com.br', '(071) 6775-8165', 'Souza', 'GO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Laís Sales', 'eda-cunha@gmail.com', '+55 31 6528 3888', 'Caldeira de da Mata', 'BA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Yasmin Vieira', 'dmoreira@ig.com.br', '0300 785 2143', 'da Paz', 'TO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('João Felipe da Luz', 'juliana93@uol.com.br', '+55 (031) 1806-3863', 'Moreira', 'CE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Alícia Alves', 'ramosmaria-cecilia@mendes.br', '71 2749 7278', 'Pinto da Serra', 'RR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Vitor Gabriel Costa', 'carolinesales@hotmail.com', '21 3880 4528', 'Pires do Norte', 'MT');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Esther Farias', 'afarias@pinto.com', '51 9076 4644', 'Pires', 'SC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('João Vitor Cunha', 'brunada-rocha@santos.br', '+55 (031) 9948-1889', 'Vieira da Serra', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Olivia Lima', 'joao-miguelcampos@da.net', '+55 51 7982 8456', 'Cunha', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Letícia das Neves', 'xlima@da.br', '81 9166-4768', 'Ribeiro do Amparo', 'SP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Alexia da Cruz', 'pietromoraes@da.br', '31 9679 0826', 'Mendes', 'SC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Stephany da Rosa', 'mendesyago@bol.com.br', '+55 (071) 1287-8887', 'Jesus do Oeste', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('João Pedro Pereira', 'da-cruzisaac@bol.com.br', '+55 84 9896 6504', 'Sales', 'RJ');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Marcos Vinicius Cavalcanti', 'samuel34@santos.br', '+55 (084) 5880 4780', 'Novaes de da Rocha', 'TO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Agatha Rezende', 'pedro-lucaspinto@nogueira.br', '(051) 7973-7323', 'Pereira de Costela', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Breno Nascimento', 'lucca33@gmail.com', '+55 81 3179-3736', 'Santos', 'AC');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Daniel Moura', 'juliaalves@da.br', '+55 21 3232-3793', 'Caldeira de Ribeiro', 'SE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Isis Viana', 'da-cruzjoana@yahoo.com.br', '31 0586 7030', 'Freitas de Goiás', 'RJ');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Srta. Emanuelly Martins', 'gabrielda-rosa@rezende.br', '+55 (051) 3345-9916', 'Silveira Verde', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Isadora Fernandes', 'melomarcos-vinicius@bol.com.br', '+55 (051) 9980-1706', 'da Cunha de Goiás', 'RJ');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Stella Moraes', 'cecilia84@caldeira.br', '+55 (021) 7836-0957', 'Costa do Norte', 'PR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Camila Araújo', 'almeidadavi-luiz@fernandes.br', '+55 84 4044-5209', 'Nunes', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Pedro Miguel Fogaça', 'da-conceicaolaura@ramos.br', '(041) 8417-4769', 'Carvalho', 'PI');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Matheus da Mota', 'lopesana-laura@ig.com.br', '+55 (031) 9915 4984', 'Pires', 'PA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Enzo Gabriel Monteiro', 'giovanna72@correia.com', '0800-972-7454', 'Lopes de Almeida', 'RO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Diego Melo', 'gustavo-henrique83@ramos.br', '41 2222-5499', 'da Rocha', 'PI');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Raul Sales', 'levicavalcanti@fernandes.br', '84 3539 7087', 'Aragão Paulista', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Enzo Gabriel Freitas', 'bruno58@yahoo.com.br', '+55 31 5214-1120', 'da Cunha', 'PI');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('João Miguel Teixeira', 'mmonteiro@yahoo.com.br', '11 8658 5266', 'Vieira de da Conceição', 'RO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Dr. Juan Melo', 'pedro-lucas71@yahoo.com.br', '(041) 9072 4007', 'Sales do Oeste', 'PB');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Ana Júlia Cardoso', 'jporto@silveira.br', '0300 412 0022', 'Alves das Pedras', 'MA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Sra. Lavínia Campos', 'xcunha@yahoo.com.br', '84 6946 1357', 'Barbosa Alegre', 'ES');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Murilo da Rocha', 'lucascunha@hotmail.com', '(071) 7060 6083', 'Silveira', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Maria Luiza Araújo', 'ysales@ig.com.br', '81 9270-3009', 'Caldeira de Jesus', 'RR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Thiago Costa', 'tcostela@gmail.com', '(021) 5710 3018', 'Farias', 'ES');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Caio Oliveira', 'luiz-otaviosilveira@bol.com.br', '+55 11 1246-1989', 'Fernandes de Moreira', 'AM');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Cecília Barros', 'ana-julia52@oliveira.br', '61 7845-9521', 'Ramos', 'AP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Sophie Nascimento', 'monteiroandre@rodrigues.com', '(031) 6419 3317', 'Cavalcanti do Campo', 'PI');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Davi Luiz Lima', 'daniela59@fernandes.br', '(021) 5973 9337', 'Nogueira de Almeida', 'PA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Luna Silva', 'usales@martins.br', '+55 (051) 3145-2673', 'Souza', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Yasmin Farias', 'kamillyda-luz@bol.com.br', '+55 31 7153 4815', 'da Paz', 'PE');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('João Lucas Fernandes', 'stephany56@fogaca.org', '71 4968 6745', 'da Luz de Porto', 'SP');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Davi da Conceição', 'fernandesluiz-gustavo@hotmail.com', '81 8054-8654', 'Farias de Caldeira', 'GO');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Maria Clara da Cruz', 'vda-rosa@pinto.br', '+55 (081) 7011-2556', 'Moura do Galho', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Kaique Silveira', 'costagustavo-henrique@da.com', '81 6355-8455', 'Fogaça do Norte', 'RR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Dr. Danilo Moraes', 'danielacosta@teixeira.com', '+55 11 8062-8758', 'Cunha', 'MS');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Eduarda da Cunha', 'alana28@da.com', '(061) 1101-3021', 'Caldeira da Praia', 'PR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Sr. Ian Moraes', 'mbarros@yahoo.com.br', '+55 (041) 3236-6653', 'Moura de da Mota', 'BA');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Dr. Heitor Barros', 'cavalcantidiego@yahoo.com.br', '(031) 7615-6472', 'Viana de Araújo', 'RN');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Anthony Alves', 'daniela55@bol.com.br', '+55 41 0626-7923', 'da Rocha', 'RR');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Caio Castro', 'npinto@da.org', '31 8463-3602', 'Viana', 'PB');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Eloah Fogaça', 'thiago52@bol.com.br', '(041) 8904-4691', 'da Luz', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Lívia Costela', 'jesuslucca@hotmail.com', '0500 509 5933', 'Duarte', 'PB');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Emanuel da Mota', 'ana-liviabarros@gmail.com', '+55 (081) 6356 5204', 'Moura', 'DF');
INSERT INTO clientes (nome, email, telefone, cidade, estado) VALUES ('Alexia da Paz', 'caioda-mata@ig.com.br', '+55 51 6766 4180', 'Pereira do Campo', 'TO');