# Use a imagem base do Python
FROM python:3.9-slim

# Essa instrução do Docker copia o script Python para o container
COPY app.py /app.py

# Essa instrução define o comando para rodar o script quando o container Docker for executado
CMD ["python", "/app.py"]