INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (1, 'Daniela da Cunha', 58, 'Dias');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (2, 'Marcos Vinicius da Mota', 25, 'Costela');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (3, 'Vitor Nascimento', 19, 'da Paz');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (4, 'Dra. Caroline Nascimento', 65, 'Mendes da Prata');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (5, 'Igor Rezende', 35, 'Nunes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (6, 'Caroline Caldeira', 33, 'Fogaça');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (7, 'Heloísa da Mata', 32, 'Lima');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (8, 'Sofia da Luz', 26, 'Cardoso');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (9, 'Thales Castro', 65, 'Nascimento de Minas');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (10, 'Dra. Maria Teixeira', 24, 'Sales');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (11, 'Srta. Luna Costa', 61, 'Moreira');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (12, 'Antônio da Rosa', 65, 'Novaes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (13, 'Ana Laura Rodrigues', 52, 'Nunes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (14, 'Sr. Thiago Freitas', 23, 'Moura do Campo');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (15, 'Vitor Gabriel Melo', 55, 'das Neves Verde');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (16, 'Luiz Gustavo da Conceição', 45, 'da Rocha');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (17, 'Srta. Ana Carolina Ferreira', 20, 'das Neves');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (18, 'Luiz Gustavo Souza', 19, 'Monteiro');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (19, 'Bárbara Sales', 23, 'Duarte');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (20, 'Agatha Martins', 31, 'Souza');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (21, 'Davi Lucas Ferreira', 32, 'da Mata');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (22, 'Luna Ribeiro', 50, 'Novaes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (23, 'João Miguel Fernandes', 56, 'Moura de Silva');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (24, 'Guilherme Farias', 19, 'Castro');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (25, 'Vitor Hugo Azevedo', 53, 'da Cunha');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (26, 'Lucas Nascimento', 30, 'Nunes de Mendes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (27, 'Nina da Cruz', 63, 'Silveira Verde');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (28, 'Bianca Oliveira', 59, 'da Luz de Cardoso');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (29, 'Bernardo Fernandes', 62, 'Farias de Viana');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (30, 'Juan da Conceição', 52, 'Sales Grande');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (31, 'Dra. Manuela da Conceição', 44, 'Teixeira da Mata');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (32, 'Felipe Lopes', 32, 'Ferreira Verde');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (33, 'Erick Farias', 46, 'Azevedo Grande');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (34, 'Ana Laura Moura', 55, 'Nascimento');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (35, 'Bárbara Farias', 35, 'Oliveira do Oeste');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (36, 'Thomas das Neves', 69, 'Silva');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (37, 'Sr. Bryan Vieira', 18, 'da Cunha de Ribeiro');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (38, 'Sr. João Gabriel Santos', 66, 'da Mata');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (39, 'Mariana Lima', 69, 'Barros do Galho');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (40, 'Dr. Rodrigo Alves', 28, 'Ribeiro do Norte');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (41, 'Juan Novaes', 62, 'Viana');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (42, 'João Guilherme da Paz', 45, 'Cardoso das Pedras');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (43, 'Lorena Aragão', 39, 'Carvalho da Prata');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (44, 'Júlia Viana', 35, 'Mendes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (45, 'João Miguel Novaes', 27, 'Campos');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (46, 'Caroline das Neves', 31, 'Silveira Verde');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (47, 'Breno Martins', 66, 'Silva da Praia');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (48, 'Benjamin Jesus', 39, 'Silveira');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (49, 'Isis Monteiro', 24, 'Araújo');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (50, 'Felipe Cardoso', 23, 'Fogaça da Serra');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (51, 'Ana Clara Nascimento', 42, 'Moreira de Caldeira');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (52, 'Maria Barbosa', 24, 'Martins de Dias');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (53, 'Vicente Silveira', 40, 'Dias de Ramos');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (54, 'Nicolas Barros', 40, 'Silva');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (55, 'Raquel Santos', 56, 'da Costa');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (56, 'Lucas Gabriel Teixeira', 34, 'Ferreira do Galho');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (57, 'Luiza das Neves', 69, 'Melo Paulista');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (58, 'Calebe Vieira', 20, 'Rocha');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (59, 'Luiza Duarte', 64, 'Teixeira');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (60, 'Ana Sophia Nascimento', 47, 'da Rocha');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (61, 'Júlia Farias', 52, 'Teixeira');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (62, 'Dr. Noah Cunha', 25, 'das Neves');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (63, 'Gabrielly Rocha', 42, 'Porto');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (64, 'Luana Barbosa', 23, 'Barros Verde');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (65, 'Srta. Amanda Ramos', 53, 'Freitas');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (66, 'Evelyn da Mota', 36, 'Jesus');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (67, 'Lorena Porto', 58, 'Martins da Praia');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (68, 'Valentina Carvalho', 57, 'Viana');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (69, 'Maysa Pereira', 41, 'Costela do Campo');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (70, 'Sr. Anthony Campos', 54, 'Martins de Novaes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (71, 'Srta. Ana Carolina Nogueira', 30, 'Monteiro');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (72, 'Thales Moreira', 63, 'Nogueira Alegre');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (73, 'Luigi Porto', 22, 'Sales de da Rosa');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (74, 'Arthur Rezende', 20, 'Porto');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (75, 'Sophia Campos', 60, 'Silva');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (76, 'Srta. Kamilly Sales', 32, 'da Luz');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (77, 'Maria da Rosa', 67, 'das Neves do Amparo');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (78, 'Ana Beatriz Melo', 36, 'da Paz');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (79, 'Emilly Gonçalves', 23, 'Nascimento do Norte');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (80, 'João Aragão', 32, 'Almeida');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (81, 'Stella Caldeira', 24, 'Ribeiro do Sul');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (82, 'Ana Lívia Peixoto', 42, 'Lopes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (83, 'Francisco Cunha', 35, 'da Costa');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (84, 'Francisco Rezende', 47, 'da Costa');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (85, 'Sr. Fernando Santos', 58, 'Barros');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (86, 'Ana Júlia Nascimento', 41, 'Araújo');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (87, 'Sr. Davi Luiz Moraes', 28, 'Nunes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (88, 'Juan Nunes', 41, 'Almeida Grande');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (89, 'Ana Clara Rocha', 40, 'Fernandes');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (90, 'Maria Alice Nascimento', 31, 'da Rocha');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (91, 'Juan Moraes', 60, 'Rodrigues Verde');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (92, 'Isis da Mata', 35, 'Teixeira das Pedras');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (93, 'Sra. Emilly Nunes', 62, 'da Luz do Norte');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (94, 'Thiago Duarte', 61, 'Nascimento');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (95, 'Emanuella Fogaça', 59, 'Lopes do Norte');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (96, 'Lavínia Lima', 22, 'Dias');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (97, 'Bianca Fernandes', 56, 'Rodrigues de Ribeiro');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (98, 'Pedro Moreira', 58, 'Vieira Paulista');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (99, 'Raul Azevedo', 28, 'da Mata');
INSERT INTO dim_cliente (id_cliente, nome, idade, cidade) VALUES (100, 'Dr. Pedro Miguel Porto', 52, 'Barbosa');